# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5bfb9e1bd131e468d6d4a04a14596232e040a9494254fc10cc81aa5d104526fda9660d203cc67b5206759346aabaf23731a87dda76f5894cbecdfeb66f79fd4e

test:
  secret_key_base: 3c973b9ec85cebfb1669a1157fcea3d8e46b697cea7f37ba14b47ced9fe67e113fe897f62561f5071d115b795f87429efec297171cab227fd665e0f157ce92e2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
